<?php
require_once __DIR__ . '/../includes/functions.php'; ensure_default_settings($pdo); require_recruiter();
$stats = get_recruiter_stats($pdo, current_user_id()); $errors = array(); $message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') { verify_csrf(); $amount = (float) str_replace(',', '.', isset($_POST['amount']) ? $_POST['amount'] : '0'); $comment = trim(isset($_POST['comment']) ? $_POST['comment'] : ''); $min = (float) get_setting($pdo, 'min_withdrawal', '500'); if ($amount < $min) { $errors[] = 'Минимальная сумма выплаты: ' . format_money($min); } if ($amount > $stats['available']) { $errors[] = 'Сумма больше доступного баланса.'; } if (!$errors) { $stmt = $pdo->prepare("INSERT INTO withdrawals (recruiter_id, amount, comment, status) VALUES (?, ?, ?, 'pending')"); $stmt->execute(array(current_user_id(), $amount, $comment)); $message = 'Заявка на выплату отправлена на проверку.'; } }
$stmt = $pdo->prepare('SELECT * FROM withdrawals WHERE recruiter_id = ? ORDER BY created_at DESC'); $stmt->execute(array(current_user_id())); $withdrawals = $stmt->fetchAll();
$pageTitle='Выплаты'; $bodyClass='app-layout'; $activePage='withdraw'; $pageHeading='Выплаты'; require __DIR__ . '/../includes/header.php'; require __DIR__ . '/../includes/recruiter-sidebar.php';
?>
<div class="recruiter-decor-2 recruiter-withdraw-decor-2" aria-hidden="true">
    <img src="<?= e(asset_url('img/recruiter-withdraw-decor-2.webp')) ?>" alt="" loading="lazy" onerror="this.style.display='none'">
</div>

<section class="stats-grid"><article class="stat-card"><span>Доступно</span><strong><?= format_money($stats['available']) ?></strong></article><article class="stat-card"><span>Уже выплачено</span><strong><?= format_money($stats['withdrawn']) ?></strong></article></section>
<section class="panel narrow-panel"><div class="panel-heading"><h2>Запросить выплату</h2></div><div class="panel-body"><div class="alert alert-warning">После получения денежных средств на свой банковский счет настоятельно рекомендуем оплатить налог в приложении "Мой налог".</div><?php if ($message): ?><div class="alert alert-success"><?= e($message) ?></div><?php endif; ?><?php if ($errors): ?><div class="alert alert-error"><?= e(implode(' ', $errors)) ?></div><?php endif; ?><form method="post" class="form-card plain-form"><?= csrf_field() ?><label>Сумма, ₽<input type="number" min="1" step="1" name="amount" required></label><label>Комментарий<textarea name="comment" rows="3"></textarea></label><button class="button" type="submit">Отправить</button></form></div></section>
<section class="panel"><div class="panel-heading"><h2>История</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Сумма</th><th>Дата</th><th>Статус</th><th>Комментарий</th></tr></thead><tbody><?php foreach ($withdrawals as $w): ?><tr><td><?= format_money($w['amount']) ?></td><td><?= e(date('d.m.Y', strtotime($w['created_at']))) ?></td><td><span class="status-pill <?= e(status_class($w['status'])) ?>"><?= e(status_label($w['status'])) ?></span></td><td><?= e($w['admin_comment']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require __DIR__ . '/../includes/recruiter-footer.php'; ?>
