<?php
require_once __DIR__ . '/../includes/functions.php';
ensure_default_settings($pdo);
require_admin();
$allowedTabs = array('verification','stats','recruiters','couriers','city-rates','news','settings');
$tab = isset($_GET['tab']) ? $_GET['tab'] : 'stats';
if (!in_array($tab, $allowedTabs, true)) { $tab = 'stats'; }
$errors = array(); $message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    $action = isset($_POST['action']) ? $_POST['action'] : '';
    try {
        if ($action === 'approve_courier') {
            $stmt = $pdo->prepare("UPDATE couriers SET status='active', rejection_reason=NULL WHERE id=? AND deleted_at IS NULL"); $stmt->execute(array((int)$_POST['id'])); $message='Курьер принят.'; $tab='verification';
        } elseif ($action === 'reject_courier') {
            $id=(int)$_POST['id']; $reason=trim($_POST['rejection_reason']); if ($reason==='') { throw new RuntimeException('Укажите причину отклонения.'); }
            $stmt=$pdo->prepare('SELECT * FROM couriers WHERE id=? LIMIT 1'); $stmt->execute(array($id)); $courier=$stmt->fetch(); if(!$courier){throw new RuntimeException('Курьер не найден.');}
            $stmt=$pdo->prepare("UPDATE couriers SET status='rejected', rejection_reason=? WHERE id=?"); $stmt->execute(array($reason,$id)); create_notification($pdo,$courier['recruiter_id'],'Курьер отклонён','Курьер '.$courier['first_name'].' '.$courier['last_name'].' отклонён. Причина: '.$reason); $message='Курьер отклонён.'; $tab='verification';
        } elseif ($action === 'approve_withdrawal' || $action === 'reject_withdrawal') {
            $status = $action === 'approve_withdrawal' ? 'approved' : 'rejected'; $stmt=$pdo->prepare("UPDATE withdrawals SET status=?, admin_comment=?, processed_at=NOW() WHERE id=? AND status='pending'"); $stmt->execute(array($status, trim($_POST['admin_comment']), (int)$_POST['id'])); $message='Заявка обработана.'; $tab='verification';
        } elseif ($action === 'save_recruiter') {
            $stmt=$pdo->prepare("UPDATE users SET full_name=?, email=? WHERE id=? AND role='recruiter'"); $stmt->execute(array(trim($_POST['full_name']), strtolower(trim($_POST['email'])), (int)$_POST['id'])); $message='Рекрутер сохранён.'; $tab='recruiters';
        } elseif ($action === 'balance_adjustment') {
            $id=(int)$_POST['id']; $amount=(float)str_replace(',', '.', $_POST['amount']); $comment=trim($_POST['comment']);
            $stmt=$pdo->prepare("UPDATE users SET balance_correction = COALESCE(balance_correction,0) + ? WHERE id=? AND role='recruiter'"); $stmt->execute(array($amount,$id));
            $stmt=$pdo->prepare('INSERT INTO balance_history (recruiter_id, admin_id, amount, comment) VALUES (?, ?, ?, ?)'); $stmt->execute(array($id,current_user_id(),$amount,$comment)); $message='Корректировка баланса сохранена.'; $tab='recruiters';
        } elseif ($action === 'delete_recruiter') {
            $stmt=$pdo->prepare("DELETE FROM users WHERE id=? AND role='recruiter'"); $stmt->execute(array((int)$_POST['id'])); $message='Рекрутер удалён.'; $tab='recruiters';
        } elseif ($action === 'save_courier') {
            $status=$_POST['status']; if(!in_array($status,array('pending','active','rejected','paused','blocked'),true)){$status='pending';}
            $stmt=$pdo->prepare('UPDATE couriers SET first_name=?, last_name=?, city=?, delivery_type=?, phone=?, status=?, rejection_reason=?, orders_count=? WHERE id=?');
            $stmt->execute(array(trim($_POST['first_name']),trim($_POST['last_name']),trim($_POST['city']),$_POST['delivery_type'],trim($_POST['phone']),$status,trim($_POST['rejection_reason']),max(0,(int)$_POST['orders_count']),(int)$_POST['id'])); $message='Курьер сохранён, доход рекрутера пересчитан.'; $tab='couriers';
        } elseif ($action === 'delete_courier') {
            $stmt=$pdo->prepare('UPDATE couriers SET deleted_at=NOW() WHERE id=?'); $stmt->execute(array((int)$_POST['id'])); $message='Курьер удалён.'; $tab='couriers';
        } elseif ($action === 'save_city_dates') {
            set_setting($pdo,'city_rates_valid_from',trim($_POST['valid_from'])); set_setting($pdo,'city_rates_valid_to',trim($_POST['valid_to'])); $message='Даты действия ставок применены.'; $tab='city-rates';
        } elseif ($action === 'save_all_city_rates') {
            $rows=json_decode(isset($_POST['rates_payload']) ? $_POST['rates_payload'] : '[]', true); if(!is_array($rows)){throw new RuntimeException('Некорректные данные ставок.');}
            $pdo->beginTransaction(); $pdo->exec('DELETE FROM city_rates');
            $stmt=$pdo->prepare('INSERT INTO city_rates (city, reward_per_order, reward_auto, reward_foot, max_earnings_per_courier) VALUES (?, ?, ?, ?, ?)');
            foreach($rows as $row){ $city=trim($row['city']); if($city===''){continue;} $auto=max(0,(int)(isset($row['auto'])?$row['auto']:(isset($row['rate'])?$row['rate']:0))); $foot=max(0,(int)(isset($row['foot'])?$row['foot']:(isset($row['rate'])?$row['rate']:$auto))); $limit=$row['limit']===''?null:max(0,(int)$row['limit']); $stmt->execute(array($city,$auto,$auto,$foot,$limit)); }
            $pdo->commit(); $message='Все изменения ставок сохранены.'; $tab='city-rates';
        } elseif ($action === 'post_news') {
            $imagePath=handle_news_image_upload('image'); $stmt=$pdo->prepare('INSERT INTO news (title, body, image_path) VALUES (?, ?, ?)'); $stmt->execute(array(trim($_POST['title']),trim($_POST['body']),$imagePath)); create_news_notification($pdo,trim($_POST['title']),trim($_POST['body']),$imagePath); $message='Новость опубликована.'; $tab='news';
        } elseif ($action === 'delete_news_image') {
            $id=(int)$_POST['id']; $stmt=$pdo->prepare('SELECT image_path FROM news WHERE id=?'); $stmt->execute(array($id)); $path=$stmt->fetchColumn(); if($path && file_exists(UPLOADS_PATH.'/'.$path)){unlink(UPLOADS_PATH.'/'.$path);} $stmt=$pdo->prepare('UPDATE news SET image_path=NULL WHERE id=?'); $stmt->execute(array($id)); $message='Изображение удалено.'; $tab='news';
        } elseif ($action === 'delete_news') {
            $stmt=$pdo->prepare('DELETE FROM news WHERE id=?'); $stmt->execute(array((int)$_POST['id'])); $message='Новость удалена.'; $tab='news';
        } elseif ($action === 'save_setting') {
            set_setting($pdo,'reward_per_order',(string)max(0,(int)$_POST['reward_per_order'])); set_setting($pdo,'min_withdrawal',(string)max(0,(int)$_POST['min_withdrawal'])); set_setting($pdo,'support_bot_url',trim($_POST['support_bot_url'])); $message='Настройки сохранены.'; $tab='settings';
        }
    } catch (Exception $ex) { if ($pdo->inTransaction()) { $pdo->rollBack(); } $errors[]=$ex->getMessage(); }
}
$activePage=$tab; $pageHeading=array('verification'=>'Проверка заявок','stats'=>'Статистика','recruiters'=>'Рекрутеры','couriers'=>'Курьеры','city-rates'=>'Ставки городов','news'=>'Новости','settings'=>'Настройки')[$tab]; $pageTitle=$pageHeading; $bodyClass='app-page'; $needsCharts=$tab==='stats';
$pendingCouriers=$pdo->query("SELECT c.*, u.full_name recruiter_name FROM couriers c JOIN users u ON u.id=c.recruiter_id WHERE c.status='pending' AND c.deleted_at IS NULL ORDER BY c.registered_at DESC")->fetchAll();
$pendingWithdrawals=$pdo->query("SELECT w.*, u.full_name recruiter_name FROM withdrawals w JOIN users u ON u.id=w.recruiter_id WHERE w.status='pending' ORDER BY w.created_at DESC")->fetchAll();
$chartData=chart_series_last_30_days($pdo);
$recruiters=$pdo->query("SELECT * FROM users WHERE role='recruiter' ORDER BY created_at DESC")->fetchAll();
$statusFilter=isset($_GET['status'])?$_GET['status']:''; $sql="SELECT c.*, u.full_name recruiter_name FROM couriers c JOIN users u ON u.id=c.recruiter_id WHERE c.deleted_at IS NULL"; if(in_array($statusFilter,array('pending','active','rejected','paused','blocked'),true)){$sql.=" AND c.status=".$pdo->quote($statusFilter);} $sql.=" ORDER BY c.registered_at DESC"; $couriers=$pdo->query($sql)->fetchAll();
$cityRates=$pdo->query('SELECT * FROM city_rates ORDER BY city')->fetchAll(); $news=$pdo->query('SELECT * FROM news ORDER BY created_at DESC LIMIT 30')->fetchAll(); $reward=get_setting($pdo,'reward_per_order','30'); $minWithdrawal=get_setting($pdo,'min_withdrawal','500'); $validFrom=get_setting($pdo,'city_rates_valid_from',''); $validTo=get_setting($pdo,'city_rates_valid_to',''); $supportBot=get_setting($pdo,'support_bot_url','https://t.me/ваш_бот');
require __DIR__ . '/../includes/header.php'; require __DIR__ . '/../includes/admin-sidebar.php';
?>

<?php if ($message): ?><div class="alert alert-success"><?= e($message) ?></div><?php endif; ?><?php if ($errors): ?><div class="alert alert-error"><?= e(implode(' ', $errors)) ?></div><?php endif; ?>
<?php if ($tab==='stats'): ?><section class="stats-grid"><article class="stat-card"><span>Рекрутеров</span><b><?= (int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='recruiter'")->fetchColumn() ?></b></article><article class="stat-card"><span>Курьеров</span><b><?= (int)$pdo->query("SELECT COUNT(*) FROM couriers WHERE deleted_at IS NULL")->fetchColumn() ?></b></article><article class="stat-card"><span>Активных</span><b><?= (int)$pdo->query("SELECT COUNT(*) FROM couriers WHERE status='active' AND deleted_at IS NULL")->fetchColumn() ?></b></article></section><section class="charts-grid"><div class="panel"><h2>Новые рекрутеры за 30 дней</h2><canvas data-chart="recruiters"></canvas></div><div class="panel"><h2>Новые курьеры за 30 дней</h2><canvas data-chart="couriers"></canvas></div><div class="panel wide"><h2>Динамика вознаграждений</h2><canvas data-chart="rewards"></canvas></div></section><script>window.adminCharts=<?= json_encode($chartData, JSON_UNESCAPED_UNICODE) ?>;</script><?php endif; ?>
<?php if ($tab==='verification'): ?><section class="panel"><div class="panel-heading"><h2>Курьеры на проверке</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Рекрутер</th><th>Курьер</th><th>Город</th><th>Телефон</th><th>Действия</th></tr></thead><tbody><?php foreach($pendingCouriers as $c): ?><tr><td><?= e($c['recruiter_name']) ?></td><td><?= e($c['first_name'].' '.$c['last_name']) ?></td><td><?= e($c['city']) ?></td><td><?= e($c['phone']) ?></td><td class="actions-cell"><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="approve_courier"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><button class="button small">Принять</button></form><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="reject_courier"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><input name="rejection_reason" placeholder="Причина"><button class="button small danger">Отклонить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><section class="panel"><div class="panel-heading"><h2>Выплаты на проверке</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Рекрутер</th><th>Сумма</th><th>Комментарий</th><th>Действия</th></tr></thead><tbody><?php foreach($pendingWithdrawals as $w): ?><tr><td><?= e($w['recruiter_name']) ?></td><td><?= format_money($w['amount']) ?></td><td><?= e($w['comment']) ?></td><td class="actions-cell"><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$w['id'] ?>"><input name="admin_comment" placeholder="Комментарий"><button class="button small" name="action" value="approve_withdrawal">Одобрить</button><button class="button small danger" name="action" value="reject_withdrawal">Отклонить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($tab==='recruiters'): ?><section class="panel"><div class="panel-heading"><h2>Рекрутеры</h2></div><div class="table-wrap"><table class="data-table wide-table"><thead><tr><th>Имя</th><th>Email</th><th>Код</th><th>Доход</th><th>Выведено</th><th>Коррекция</th><th>Баланс</th><th>Действия</th></tr></thead><tbody><?php foreach($recruiters as $r): $gross=calculate_recruiter_gross($pdo,$r['id']); $approved=approved_withdrawals_amount($pdo,$r['id']); $balance=calculate_recruiter_balance($pdo,$r['id']); ?><tr><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_recruiter"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><td><input name="full_name" value="<?= e($r['full_name']) ?>"></td><td><input type="email" name="email" value="<?= e($r['email']) ?>"></td><td><code><?= e($r['referral_code']) ?></code></td><td><?= format_money($gross) ?></td><td><?= format_money($approved) ?></td><td><?= format_money($r['balance_correction']) ?></td><td><b><?= format_money($balance) ?></b></td><td class="actions-cell"><button class="button small">Сохранить</button></form><button class="button small" data-modal-open="balance-<?= (int)$r['id'] ?>">Корректировка баланса</button><form method="post" data-confirm="Удалить рекрутера?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_recruiter"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="button small danger">Удалить</button></form><dialog id="balance-<?= (int)$r['id'] ?>" class="modal"><form method="post" class="form-card"><?= csrf_field() ?><input type="hidden" name="action" value="balance_adjustment"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><h3>Корректировка баланса</h3><label>Сумма (+ или -)<input type="number" step="0.01" name="amount" required></label><label>Комментарий<input name="comment" required></label><button class="button">Сохранить</button><button class="button button-outline" type="button" data-modal-close>Закрыть</button></form></dialog></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($tab==='couriers'): ?><section class="panel"><div class="panel-heading"><h2>Курьеры</h2><form><input type="hidden" name="tab" value="couriers"><select name="status" onchange="this.form.submit()"><option value="">Все статусы</option><?php foreach(array('pending','active','rejected','paused','blocked') as $s): ?><option value="<?= e($s) ?>" <?= $statusFilter===$s?'selected':'' ?>><?= e(status_label($s)) ?></option><?php endforeach; ?></select></form></div><div class="table-wrap"><table class="data-table wide-table"><thead><tr><th>Рекрутер</th><th>Имя</th><th>Город</th><th>Тип</th><th>Телефон</th><th>Статус</th><th>Причина</th><th>Заказы</th><th>Действия</th></tr></thead><tbody><?php foreach($couriers as $c): ?><tr><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_courier"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><td><?= e($c['recruiter_name']) ?></td><td><input name="first_name" value="<?= e($c['first_name']) ?>"><input name="last_name" value="<?= e($c['last_name']) ?>"></td><td><input name="city" value="<?= e($c['city']) ?>"></td><td><select name="delivery_type"><option value="auto" <?= $c['delivery_type']==='auto'?'selected':'' ?>>Авто</option><option value="foot" <?= $c['delivery_type']==='foot'?'selected':'' ?>>Пешим</option><option value="bike" <?= $c['delivery_type']==='bike'?'selected':'' ?>>Вело</option></select></td><td><input name="phone" value="<?= e($c['phone']) ?>"></td><td><select name="status"><?php foreach(array('pending','active','rejected','paused','blocked') as $s): ?><option value="<?= e($s) ?>" <?= $c['status']===$s?'selected':'' ?>><?= e(status_label($s)) ?></option><?php endforeach; ?></select></td><td><input name="rejection_reason" value="<?= e($c['rejection_reason']) ?>"></td><td><input type="number" min="0" name="orders_count" value="<?= (int)$c['orders_count'] ?>"></td><td class="actions-cell"><button class="button small">Сохранить</button></form><form method="post" data-confirm="Удалить курьера?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_courier"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><button class="button small danger">Удалить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($tab==='city-rates'): ?><section class="panel"><div class="panel-heading"><h2>Период действия городских ставок</h2></div><form method="post" class="form-row"><?= csrf_field() ?><input type="hidden" name="action" value="save_city_dates"><label>С<input type="date" name="valid_from" value="<?= e($validFrom) ?>"></label><label>По<input type="date" name="valid_to" value="<?= e($validTo) ?>"></label><button class="button">Применить даты</button></form><p class="muted">Сейчас ставки <?= city_rates_active($pdo) ? 'активны' : 'не применяются — используется глобальная ставка' ?>.</p></section><section class="panel"><div class="panel-heading"><h2>Редактируемая таблица ставок</h2><button class="button small" type="button" data-add-rate>Добавить город</button></div><form method="post" data-city-rates-form><?= csrf_field() ?><input type="hidden" name="action" value="save_all_city_rates"><input type="hidden" name="rates_payload" data-rates-payload><div class="table-wrap"><table class="data-table" data-rates-table><thead><tr><th>Город</th><th>Ставка на авто</th><th>Ставка пешим</th><th>Лимит на курьера</th><th></th></tr></thead><tbody><?php foreach($cityRates as $rate): $legacy=(int)$rate['reward_per_order']; $auto=(int)(isset($rate['reward_auto']) ? $rate['reward_auto'] : $legacy); $foot=(int)(isset($rate['reward_foot']) ? $rate['reward_foot'] : $legacy); ?><tr><td><input value="<?= e($rate['city']) ?>" data-rate-city readonly></td><td><input type="number" min="0" value="<?= $auto > 0 ? $auto : $legacy ?>" data-rate-auto readonly></td><td><input type="number" min="0" value="<?= $foot > 0 ? $foot : $legacy ?>" data-rate-foot readonly></td><td><input type="number" min="0" value="<?= e($rate['max_earnings_per_courier']) ?>" data-rate-limit readonly placeholder="Без лимита"></td><td><button class="button small" type="button" data-edit-rate title="Редактировать"><i class="fa-solid fa-pen"></i></button><button class="button small danger" type="button" data-remove-rate>Удалить</button></td></tr><?php endforeach; ?></tbody></table></div><button class="button">Сохранить все изменения</button></form></section><?php endif; ?>
<?php if ($tab==='news'): ?><section class="panel narrow-panel"><div class="panel-heading"><h2>Опубликовать новость</h2></div><form method="post" enctype="multipart/form-data" class="form-card plain-form"><?= csrf_field() ?><input type="hidden" name="action" value="post_news"><label>Заголовок<input name="title" required></label><label>Текст<textarea name="body" rows="5" required></textarea></label><label>Изображение WebP/JPG/PNG до 2 МБ<input type="file" name="image" accept="image/webp,image/jpeg,image/png"></label><button class="button">Опубликовать</button></form></section><section class="panel"><div class="panel-heading"><h2>Последние новости</h2></div><div class="news-list"><?php foreach($news as $n): ?><article><h3><?= e($n['title']) ?></h3><?php if($n['image_path']): ?><img class="news-image" src="<?= e(upload_url($n['image_path'])) ?>" alt="<?= e($n['title']) ?>" loading="lazy"><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete_news_image"><input type="hidden" name="id" value="<?= (int)$n['id'] ?>"><button class="button small danger">Удалить изображение</button></form><?php endif; ?><p><?= e($n['body']) ?></p><time><?= e(date('d.m.Y H:i', strtotime($n['created_at']))) ?></time><form method="post" data-confirm="Удалить новость?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_news"><input type="hidden" name="id" value="<?= (int)$n['id'] ?>"><button class="button small danger">Удалить</button></form></article><?php endforeach; ?></div></section><?php endif; ?>
<?php if ($tab==='settings'): ?><section class="panel narrow-panel"><div class="panel-heading"><h2>Настройки</h2></div><form method="post" class="form-card plain-form"><?= csrf_field() ?><input type="hidden" name="action" value="save_setting"><label>Глобальная ставка, ₽<input type="number" min="0" name="reward_per_order" value="<?= (int)$reward ?>"></label><label>Минимальная выплата, ₽<input type="number" min="0" name="min_withdrawal" value="<?= (int)$minWithdrawal ?>"></label><label>Telegram-бот поддержки<input name="support_bot_url" value="<?= e($supportBot) ?>"></label><button class="button">Сохранить</button></form></section><?php endif; ?>
<?php require __DIR__ . '/../includes/admin-footer.php'; ?>
